import Head from 'next/head'
import Link from 'next/link'
import About from '../components/About'
import Contact from '../components/Contact'
import Experience from '../components/Experience'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import { HomeIcon } from '@heroicons/react/24/solid'
import { fetchPageInfo } from '../utils/fetchPageInfo'
import { fetchSkills } from '../utils/fetchSkill'
// import { fetchExperience } from '../utils/fetchExperience'
import { fetchProject } from '../utils/fetchProject'
import { fetchSocials } from '../utils/fetchSocials'

export default function Home(props) {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll z-0 overflow-x-hidden scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]/60'>
      <Head>
        <title>Yulius Kevin</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/* Headers */}
      <Header socials={props.social}/>

      {/* Hero */}
      <div id='home' className='snap-start '>
        <Hero pageInfo={props.pageInfo}/>
      </div>

      {/* About */}
      <div id='about' className='snap-center'>
        <About pageInfo={props.pageInfo}/>
      </div>

      {/* Experience */}
      {/* <section className='snap-center scroll-smooth' id='experience'>
        <Experience/>
      </section> */}

      {/* Skills */}
      <div id='skills' className='snap-start'>
        <Skills skill={props.skills}/>
      </div>

      {/* Projects */}
      <div id='projects' className='snap-start'>
        <Projects project={props.projects}/>
      </div>

      {/* Contact Me */}
      <div id='contact' className='snap-start'>
        <Contact pageInfo={props.pageInfo}/>
      </div>

      <Link href='#home'>
      <div className='sticky bottom-5 w-full cursor-pointer'>
        <div className='flex items-center justify-center'>
          <HomeIcon className='h-10 w-10 rounded-full filter grayscale hover:grayscale-0 cursor-pointer text-[#F7AB0A]'/>
        </div>
      </div>
      </Link>
    </div>
  )
}

export const getStaticProps = async () => {
  const pageInfo = await fetchPageInfo();
  // const experiences = await fetchExperience();
  const skills = await fetchSkills();
  const projects = await fetchProject();
  const social = await fetchSocials();
  // experiences,

  return {
    props : {
      pageInfo,
      skills,
      projects,
      social
    },
    revalidate : 10,
  }
}